name: Rust

on:
 release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: zhanghanyun/actionts@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
